version: '3'
services:
  logbot:
    build: .        
    ports:
      - "127.0.0.1:9004:8000"
    volumes:
      - "/opt/zfx-logbot:/mnt"
    environment:
      - "LUA_PATH=./?/init.lua;./?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua"
